### PR TITLE
Move to GH Actions

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse I need your approvement for this PR because I have removed `common` directory

**Comment by ronaldtse** [comment]
@CAMOBAP795 there's a build that's failing. Can you have a look?

**Comment by ronaldtse** [comment]
Also I think we need to change GHA to build on "pull_request" and only on "master" branch to prevent double builds. Thanks!

**Comment by CAMOBAP** [comment]
> Also I think we need to change GHA to build on "pull_request" and only on "master" branch to prevent double builds. Thanks!

Agree, we already have this in config
```
on:
  push:
    branch: master
  pull_request:
    branches:
    - '**'
```

And AFAIR it worked previously but looks broken now, investigating why

**Comment by CAMOBAP** [comment]
@ronaldtse done! if no other objections I will proceed with merge

**Pull request merged**
