### PR TITLE
Update IETF templates workflow

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
Tracked here: https://github.com/metanorma/metanorma/issues/228

**Comment by CAMOBAP** [comment]
@ronaldtse I suppose this PR should be closed without merging because the same changes were done in https://github.com/metanorma/mn-templates-ietf/pull/25

Another 'round' of improvements will be done after https://github.com/metanorma/mn-templates-ogc/pull/46

**Comment by ronaldtse** [comment]
> I suppose this PR should be closed without merging because the same changes were done in #25

Can we be sure that the new 'round' of improvements will cover all the workflow tasks in this PR? Thanks.

**Comment by manuelfuenmayor** [comment]
Workflow is already fixed in master branch. Closing.

**Comment by ronaldtse** [comment]
Thanks guys!

**Pull request closed without merging**
