### PR TITLE
Update AsciiDoc markup to AsciiRFC v3

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
*From https://github.com/metanorma/mn-templates-ietf/issues/6*

Here, the only updates that I considered necessary were the *anchors markup*. Unless you want me to add additional content to illustrate other markups. Please let me know if I should make further changes.

Thanks!

### CODE REVIEW

**Comment by ronaldtse** [comment]
Yes, the documents are not compiling because the syntax has changed. We should have a "migration guide for metanorma-ietf v1 to v2": I just did one yesterday...

1. In `:mn-output-extensions:`, the output format is now `rfc` not `xmlrfc2` or `xmlrfc3`. (because we only support xmlrfc3 now)
2. `:submissionType:` is now `:submission-type:`
3. The `:status:`, `:intended-series` values are very picky in xml2rfc (xml2rfc will balk at the values `full-standard` and `standard`, `info` works)
4. The references sections have changed -- the mechanism to do RFC references is via auto-fetch and manual entry.

e.g. instead of:
```adoc
++++
<reference anchor="RFC2119"
  target="https://www.rfc-editor.org/info/rfc2119">
  <front>
    <title>Key words for use in RFCs to Indicate
      Requirement Levels</title>
    <author initials="S." surname="Bradner" fullname="S. Bradner">
      <organization/>
    </author>
    <date year="1997" month="March"/>
  </front>
  <seriesInfo name="BCP" value="14"/>
  <seriesInfo name="RFC" value="2119"/>
  <seriesInfo name="DOI" value="10.17487/RFC2119"/>
</reference>
++++
```

Do (for IETF RFCs, I-Ds, and other standard documents):
```
* [[[RFC2119,RFC 2119]]]
```

For custom bibliographic items, instead of:

```adoc
++++
<reference anchor="grail_film">
  <front>
    <title>Monty Python and the Holy Grail</title>
    <author initials="G." surname="Chapman"/>
    <author initials="J." surname="Cleese"/>
    <author initials="E." surname="Idle"/>
    <author initials="T." surname="Gilliam"/>
    <author initials="T." surname="Jones"/>
    <author initials="M." surname="Palin"/>
    <date year="1975"/>
  </front>
</reference>
++++
```

Do this:
```adoc
[%bibitem]
== Monty Python and the Holy Grail
id:: grail_film
contributor::
contributor.person.name.initial:: G.
contributor.person.name.surname:: Chapman
contributor::
contributor.person.name.initial:: J.
contributor.person.name.surname:: Cleese
contributor::
contributor.person.name.initial:: E.
contributor.person.name.surname:: Idle
contributor::
contributor.person.name.initial:: T.
contributor.person.name.surname:: Gilliam
contributor::
contributor.person.name.initial:: T.
contributor.person.name.surname:: Jones
contributor::
contributor.person.name.initial:: M.
contributor.person.name.surname:: Palin
date::
date.type:: published
date.value:: 1975
```

**Comment by manuelfuenmayor** [comment]
Thanks @ronaldtse  for the clarification! I'm updating the files.

**Comment by manuelfuenmayor** [comment]
Changes applied.
I couldn't find a proper identifier of `IETF.TLP` (https://trustee.ietf.org/trust-legal-provisions.html) to enable auto-fetch. I tried several combinations with no success, and ended up putting `IETF TRUST`.
@ronaldtse, could you tell me how should it be written, please?

**Comment by ronaldtse** [comment]
> I couldn't find a proper identifier of IETF.TLP (https://trustee.ietf.org/trust-legal-provisions.html) to enable auto-fetch. I tried several combinations with no success, and ended up putting IETF TRUST.


It has to be placed as a normal reference as this doesn't support auto-fetch (only IETF RFCs and IETF Internet-Drafts support that).

BTW how come there is a single Bibliography section? In RFC documents Normative References and Informative References are in separate sections.

**Comment by manuelfuenmayor** [comment]
> BTW how come there is a single Bibliography section? In RFC documents Normative References and Informative References are in separate sections.

Oh, well, given that the previous approach didn't render properly, I thought maybe it should be a mistake in the markup. So I followed [Nick's documentation](metanorma.com/author/topics/document-format/bibliography/#general) on reference subsection, and got a "proper" rendering. (But maybe I did wrong.)

**Comment by ronaldtse** [comment]
@manuel489 
The "normal" bibliography guidance differs from IETF, where the Normative References and Informative References are two separate sections, and that the Informative References section is optional.

We should update metanorma.com for that. Thanks!

**Comment by manuelfuenmayor** [comment]
> The "normal" bibliography guidance differs from IETF, where the Normative References and Informative References are two separate sections, and that the Informative References section is optional.

Ok, correction applied.

**Pull request merged**
