### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by CAMOBAP**
https://github.com/metanorma/metanorma-cli/issues/93

### CODE REVIEW

**Review by ronaldtse — COMMENTED** [review]
Type should be set to “ietf”.

**Comment by CAMOBAP** [comment]
@ronaldtse usually we have `document.adoc` file in the root of doctype directory, here we have only `adoc` in sections

What should we compile in such case?

**Comment by ronaldtse** [comment]
The “document.adoc” is given under rfc/ directory.

**Comment by CAMOBAP** [comment]
@opoudjis @ronaldtse it this expected behavior that `metanorma-cli` looks for `rfc2629.dtd` in cwd instead `adoc` path

```
[metanorma-ietf] Validation error: fatal: file not found: /home/travis/build/metanorma/mn-templates-ietf/rfc2629.dtd (No such file or directory)
```

Thanks,

**Comment by ronaldtse** [comment]
@CAMOBAP795, can you help fix this issue? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse https://github.com/metanorma/metanorma-ietf/pull/32 ready for review

**Comment by CAMOBAP** [comment]
@ronaldtse I propose to merge this PR

**Pull request merged**
